name: Deploy Example #action名称
on: [push] #在推送的时候运行此action

jobs:
  build_job:
    runs-on: ubuntu-latest  #运行环境
    name: build
    steps:
      # check out the repository
      - name: Checkout    
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: dist
